#!/usr/bin/env python3
import sys
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
import client


def main():
    if len(sys.argv) != 3:
        print("Usage: ./rep_subject_credentials <password> <credentials_file>")
        sys.exit(1)

    password = sys.argv[1]
    credentials_file = sys.argv[2]

    client.subject_credentials(password, credentials_file)

if __name__ == "__main__":
    main()