#!/usr/bin/env python3
import sys
import json
import client
import requests

def main():
    if len(sys.argv) != 4:
        print("Usage: ./rep_add_doc <session file> <document name> <file>")
        sys.exit(1)

    session_file = sys.argv[1]
    document_name = sys.argv[2]
    file_path = sys.argv[3]
    client.add_doc(session_file, document_name, file_path)

if __name__ == "__main__":
    main()