#!/usr/bin/env python3

import json
import sys
import client
import requests

def main():
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print("Usage: ./rep_list_subjects <session file> [username] ")
        sys.exit(1)

    session_file = sys.argv[1]
    username = sys.argv[2] if len(sys.argv) == 3 else None

    client.list_subjects(session_file, username)

if __name__ == "__main__":
    main()

