#!/usr/bin/env python3
import base64
import hashlib
import json
import sys
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend
from base64 import b64decode
import client

def main():

    if len(sys.argv) != 3:
        print("Usage: ./rep_decrypt_file <encrypted_file> <metadata>")
        sys.exit(1)
    
    encrypted_file_path = sys.argv[1]
    metadata_path = sys.argv[2]
    client.decrypt_file(encrypted_file_path, metadata_path)


if __name__ == "__main__":
    main()
