#!/usr/bin/env python3
import sys
import json
import requests
import client

def main():
    if len(sys.argv) != 3:
        print("Usage: ./rep_get_doc_metadata <session_file> <document_name>")
        sys.exit(1)

    session_file = sys.argv[1]
    document_name = sys.argv[2]

    client.rep_get_doc_metadata(session_file, document_name)

if __name__ == "__main__":
    main()