#!/usr/bin/env python3
import sys
import json
import client
import requests

def main():
    if len(sys.argv) != 3:
        print("Usage: ./rep_drop_role <session file> <role>")
        sys.exit(1)

    session_file = sys.argv[1]
    role = sys.argv[2]
    client.drop_role(session_file, role)
    
    
if __name__ == "__main__":
    main()