#!/usr/bin/env python3
import sys
import json
import client
import requests

def main():
    if len(sys.argv) != 4:
        print("Usage: ./rep_add_permission <session file> <role> <username> or ./rep_add_permission <session file> <role> <permission>")
        sys.exit(1)

    session_file = sys.argv[1]
    role = sys.argv[2]
    username_permission = sys.argv[3]
    if username_permission in ["ROLE_NEW", "ROLE_DOWN", "ROLE_UP", "ROLE_MOD", "ROLE_ACL", "SUBJECT_NEW", "SUBJECT_DOWN", "SUBJECT_UP", "DOC_NEW"]:
        client.add_permission_role(session_file, role, username_permission)
    else:
        client.add_permission_user(session_file, role, username_permission)
    
    
if __name__ == "__main__":
    main()