#!/usr/bin/env python3
import sys
import json
import client
import requests

def main():
    if len(sys.argv) != 5 and len(sys.argv) != 6:
        print("Usage: ./rep_acl_doc <session file> <document name> [+/-] <role> <permission>")
        sys.exit(1)

    session_file = sys.argv[1]
    document_name = sys.argv[2]
    adding = True
    if len(sys.argv) == 6:
        if sys.argv[3] == "+":
            adding = True
        elif sys.argv[3] == "-":
            adding = False
        else:
            print("Usage: ./rep_acl_doc <session file> <document name> [+/-] <role> <permission>")
            sys.exit(1)
        role = sys.argv[4]
        permission = sys.argv[5]
    else:
        role = sys.argv[3]
        permission = sys.argv[4]



    
    client.acl_doc(session_file, document_name, role, permission, adding)

if __name__ == "__main__":
    main()