#!/usr/bin/env python3

import sys
import requests
import client

def main():
    if len(sys.argv) != 3:
        print("Usage: ./rep_delete_doc <session_file> <document_name>")
        sys.exit(1)
        
    session_file = sys.argv[1]
    document_name = sys.argv[2]
    client.delete_document(session_file, document_name)

if __name__ == "__main__":
    main()